package io.slin.gradle

/**
 * Manages the cache file (env or properties) including age check.
 *
 * Rules:
 *   file missing or older than maxAge   load and write
 *   file present and fresh              do nothing
 *   load fails (source unreachable)     keep the existing file
 */
class SecretFileService {

    final File file
    final String format        // 'env' or 'properties'
    final long maxAgeMillis

    SecretFileService(File file, String format, long maxAgeMillis) {
        this.file = file
        this.format = format
        this.maxAgeMillis = maxAgeMillis
    }

    boolean exists() { file.exists() }

    boolean isFresh() {
        if (!file.exists()) return false
        long age = System.currentTimeMillis() - file.lastModified()
        return age < maxAgeMillis
    }

    long ageMillis() {
        file.exists() ? System.currentTimeMillis() - file.lastModified() : Long.MAX_VALUE
    }

    void write(Map<String, String> entries) {
        file.parentFile?.mkdirs()
        if (format == 'properties') {
            def props = new Properties()
            entries.each { k, v -> props.setProperty(k, v ?: '') }
            file.withOutputStream { os ->
                props.store(os, 'generated by slin-secrets plugin')
            }
        } else {
            // env format: KEY=VALUE, line breaks escaped
            def sb = new StringBuilder()
            sb.append('# generated by slin-secrets plugin\n')
            entries.each { k, v ->
                def safe = (v ?: '').replace('\\', '\\\\').replace('\n', '\\n').replace('\r', '')
                sb.append("${k}=${safe}\n")
            }
            file.text = sb.toString()
        }
    }

    Map<String, String> read() {
        def result = [:] as LinkedHashMap
        if (!file.exists()) return result

        if (format == 'properties') {
            def props = new Properties()
            file.withInputStream { props.load(it) }
            props.each { k, v -> result[k.toString()] = v?.toString() }
        } else {
            file.eachLine { line ->
                def trimmed = line.trim()
                if (!trimmed || trimmed.startsWith('#')) return
                int idx = trimmed.indexOf('=')
                if (idx < 0) return
                def key = trimmed.substring(0, idx)
                def val = trimmed.substring(idx + 1).replace('\\n', '\n').replace('\\\\', '\\')
                result[key] = val
            }
        }
        return result
    }

    /** Parses "30m", "2h", "1d", "45s" or a plain number (meaning minutes). */
    static long parseMaxAgeMillis(String spec) {
        if (!spec) return 3_600_000L  // default 1h
        def m = (spec.trim() =~ /^(\d+)\s*([smhd]?)$/)
        if (!m.matches()) {
            throw new IllegalArgumentException("Invalid maxAge: '${spec}' (allowed for example 30m, 2h, 1d)")
        }
        long n = (m[0][1] as long)
        switch (m[0][2]) {
            case 's': return n * 1_000L
            case 'h': return n * 3_600_000L
            case 'd': return n * 86_400_000L
            case 'm':
            default:  return n * 60_000L
        }
    }
}
